/* tslint:disable */
/* eslint-disable */
/**
 * Akeneo PIM REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PostProductsRequestAssociationsAssociationTypeCode } from './PostProductsRequestAssociationsAssociationTypeCode';
import {
    PostProductsRequestAssociationsAssociationTypeCodeFromJSON,
    PostProductsRequestAssociationsAssociationTypeCodeFromJSONTyped,
    PostProductsRequestAssociationsAssociationTypeCodeToJSON,
} from './PostProductsRequestAssociationsAssociationTypeCode';

/**
 * Several associations related to groups, product models and/or other products, grouped by association types
 * @export
 * @interface PostProductsRequestAssociations
 */
export interface PostProductsRequestAssociations {
    /**
     * 
     * @type {PostProductsRequestAssociationsAssociationTypeCode}
     * @memberof PostProductsRequestAssociations
     */
    associationTypeCode?: PostProductsRequestAssociationsAssociationTypeCode;
}

/**
 * Check if a given object implements the PostProductsRequestAssociations interface.
 */
export function instanceOfPostProductsRequestAssociations(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PostProductsRequestAssociationsFromJSON(json: any): PostProductsRequestAssociations {
    return PostProductsRequestAssociationsFromJSONTyped(json, false);
}

export function PostProductsRequestAssociationsFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostProductsRequestAssociations {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'associationTypeCode': !exists(json, 'associationTypeCode') ? undefined : PostProductsRequestAssociationsAssociationTypeCodeFromJSON(json['associationTypeCode']),
    };
}

export function PostProductsRequestAssociationsToJSON(value?: PostProductsRequestAssociations | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'associationTypeCode': PostProductsRequestAssociationsAssociationTypeCodeToJSON(value.associationTypeCode),
    };
}

