/* tslint:disable */
/* eslint-disable */
/**
 * Akeneo PIM REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Several associations related to groups, product models and/or other products, grouped by association types
 * @export
 * @interface ProductsEmbeddedItemsInnerAllOf1Associations
 */
export interface ProductsEmbeddedItemsInnerAllOf1Associations {
    /**
     * 
     * @type {object}
     * @memberof ProductsEmbeddedItemsInnerAllOf1Associations
     */
    additionalProperties?: object;
}

/**
 * Check if a given object implements the ProductsEmbeddedItemsInnerAllOf1Associations interface.
 */
export function instanceOfProductsEmbeddedItemsInnerAllOf1Associations(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ProductsEmbeddedItemsInnerAllOf1AssociationsFromJSON(json: any): ProductsEmbeddedItemsInnerAllOf1Associations {
    return ProductsEmbeddedItemsInnerAllOf1AssociationsFromJSONTyped(json, false);
}

export function ProductsEmbeddedItemsInnerAllOf1AssociationsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductsEmbeddedItemsInnerAllOf1Associations {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'additionalProperties': !exists(json, 'additionalProperties') ? undefined : json['additionalProperties'],
    };
}

export function ProductsEmbeddedItemsInnerAllOf1AssociationsToJSON(value?: ProductsEmbeddedItemsInnerAllOf1Associations | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'additionalProperties': value.additionalProperties,
    };
}

